name: Node.js CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.4"
      - run: npm ci
        working-directory: core/
      - run: npm ci
        working-directory: cli/
      - run: npm run lint
        working-directory: core/
      - run: npm run lint
        working-directory: cli/
      - run: npm run build
        working-directory: core/
      - run: npm run build
        working-directory: cli/
